apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: janitor
spec:
  version: {{ .TagName }}
  homepage: https://github.com/dastergon/kubectl-janitor
  shortDescription: Lists objects in a problematic state
  description: |
    Troubleshooting Kubernetes clusters sometimes requires
    a combination of kubectl commands and other command-line tools
    such as jq to do correlations around the issues that the various
    objects might have. Moreover, sometimes the supported options
    of the --field-selector flag might be limited as well.
    This plugin assists in finding Kubernetes objects in a problematic state.
    It currently supports Job, Pod, PersistentVolume,
    and PersistentVolumeClaim resources.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/dastergon/kubectl-janitor/releases/download/{{ .TagName }}/kubectl-janitor_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-janitor
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/dastergon/kubectl-janitor/releases/download/{{ .TagName }}/kubectl-janitor_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-janitor
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/dastergon/kubectl-janitor/releases/download/{{ .TagName }}/kubectl-janitor_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-janitor.exe
